In [1]:
from graph_datamodule import Triplet_Dataset
FILE_PATH = '/home/jj/CILProject22/data/raw/cross_validation/test_split_0.csv'

In [2]:
d = Triplet_Dataset(file_path=FILE_PATH, n_users=1000, n_items=10000, k=2)

In [3]:
d.__getitem__(0)

(tensor([   0, 1066]),
 tensor([2207]),
 tensor([667]),
 tensor([806, 962, 767, 150, 675]),
 tensor([1507, 5120, 1906, 4387, 7620]),
 tensor([[ 401, 7448, 6760,  523, 3495],
         [5992, 3392, 7148, 2904, 7644]]))

In [7]:
import torch
from torch.utils.data import DataLoader

In [6]:
dataloader = DataLoader(d, batch_size=32, shuffle=True)
for t in dataloader:
    print(t)
    break

[tensor([[   0, 1089],
        [   0, 1066]]), tensor([[ 7917],
        [10841]]), tensor([[340],
        [ 23]]), tensor([[757, 550, 799,  19,  84],
        [178,  66, 266, 706, 532]]), tensor([[ 2659,  7537, 10027,  6022, 10974],
        [10483,  7256,  7584,  7532, 10142]]), tensor([[[  782,  1181,  8305,  5156,  7223],
         [ 5837,  5144,  7719, 10160,   201]],

        [[ 2007,  2837,  2083,  5319,  1540],
         [ 7409,  7293,  8712,  7059,  4531]]])]


In [8]:
def collate_tuples(batch):
    #print(len(batch))
    #print(batch)
    batch = list(zip(*batch))
    #print(batch)
    for i, _ in enumerate(batch):
        batch[i] = torch.stack(batch[i])
    # print(batch[0].size())
    return tuple(batch)

In [12]:
dataloader = DataLoader(d, batch_size=4, collate_fn=collate_tuples)
for t in dataloader:
    print(t)
    print(t[4].size())
    break

4
[(tensor([   0, 1066]), tensor([2001]), tensor([370]), tensor([469, 228, 822, 415, 908]), tensor([4889, 4311, 5203, 1626, 2790]), tensor([[  910,  2313,  7956,  5311,  3012],
        [ 6024,  7188,  2760,  8212, 10297]])), (tensor([   0, 1089]), tensor([4266]), tensor([937]), tensor([682, 981, 603, 267, 506]), tensor([2544, 3646, 1366, 8333, 3723]), tensor([[ 6862, 10605,  4959,  2341,  3100],
        [ 1824,  1602,  7567,  8860,  8569]])), (tensor([   0, 1113]), tensor([1114]), tensor([261]), tensor([956, 992, 784, 349, 316]), tensor([1429, 2090, 6395, 3802, 7557]), tensor([[ 8035,  8225,  3467,  1728,  6295],
        [10727, 10030,  3527,  6763,  9983]])), (tensor([   0, 1181]), tensor([8951]), tensor([546]), tensor([ 94, 935, 601, 552, 208]), tensor([1885, 1798, 4920, 3646, 6783]), tensor([[ 7015,  9692,  2780,  4943,  9271],
        [ 5291,  5044,  9978,  7569, 10485]]))]
[(tensor([   0, 1066]), tensor([   0, 1089]), tensor([   0, 1113]), tensor([   0, 1181])), (tensor([2001]), t

In [5]:
d.__len__()

470782

In [6]:
d.len

470782