In [1]:
import pandas as pd
import numpy as np

In [2]:
# read in the data
path = '/home/jimmy/CILProject22/data/raw/train_split_0.csv'

In [3]:
from src.data.Contrastive.graph_datamodule import Triplet_Dataset
dataset = Triplet_Dataset(file_path=path, n_users=1000, n_items=10000, k=2)


In [4]:
from torch.utils.data import DataLoader
from src.data.Contrastive.graph_datamodule import collate_tuples
dataloader = DataLoader(dataset, batch_size=32, collate_fn=collate_tuples, shuffle=True)

In [34]:
# Create Model Object
x, y, x_neighbors, y_neighbors, x_negative, y_negative, negative_x, negative_y = dataset.__getitem__(0)

In [14]:
dataset.__getitem__(0)

(tensor(0),
 tensor(1043),
 tensor([3110]),
 tensor([518]),
 tensor([136, 759, 391, 887, 301]),
 tensor([2800, 2420, 1221, 8409, 2502]),
 tensor([7867, 8709, 5047,  334, 3306]),
 tensor([9975, 2383, 9820, 4897, 4160]))

In [5]:
from src.models.CSE.model import model
model = model()

In [10]:
for i, batch in enumerate(dataloader):
    x, y, x_neighbors, y_neighbors, x_negative, y_negative, negative_x, negative_y = batch

        # if x >= 1000:
        #     x, y, = y, x
        #     x_neighbors, y_neighbors = y_neighbors, x_neighbors
        #     x_negative, y_negative = y_negative, x_negative

    phi_x, _, _ = model.forward(x)
    phi_y, _,  _ = model.forward(y)
    _, _, phi_UC = model.forward(x_neighbors)
    _, _, phi_UC_negative = model.forward(x_negative)
    phi_UC_negative = phi_UC_negative.transpose(0, 1)
    print(phi_UC_negative.size())
    _, phi_IC, _ = model.forward(y_neighbors)

    _, phi_IC_negative, _ = model.forward(y_negative)
    print(phi_IC_negative)
    phi_IC_negative = phi_IC_negative.transpose(0, 1)

    phi_negative_x, _, _ = model.forward(negative_x)
    phi_negative_y, _, _ = model.forward(negative_y)

    loss = model.loss(phi_x, phi_y, phi_IC, phi_UC, phi_IC_negative, phi_UC_negative,
                         phi_negative_x, phi_negative_y)
    break

torch.Size([5, 32, 10])
tensor([[[-0.9591,  2.3153,  0.3744,  ..., -0.5515, -0.1637,  2.0266],
         [ 1.0553,  1.5757, -0.0036,  ...,  2.8410, -2.1138,  0.9335],
         [-0.1254, -0.1643, -1.8590,  ...,  0.7996,  1.1335, -0.8498],
         [ 1.1816, -0.6340,  1.3392,  ...,  0.3994,  0.7771,  1.4208],
         [ 0.9428, -0.8355,  0.7133,  ..., -0.1068, -0.0240, -0.6032]],

        [[-0.3428, -1.3775, -1.6344,  ..., -0.4915, -0.2481, -0.1378],
         [-1.0815, -2.1510,  0.8457,  ...,  0.5941,  0.4146, -0.7981],
         [-1.1398, -2.2350, -0.1699,  ...,  0.7004,  0.4143, -1.4088],
         [ 0.1989, -0.7728, -0.7864,  ...,  0.4950, -0.5320, -0.7167],
         [-0.8815, -0.3384,  0.9674,  ...,  0.1892,  2.1888, -1.0124]],

        [[ 1.0010,  0.8335,  0.0372,  ...,  0.4649, -1.0999, -1.2055],
         [ 0.0053,  0.5733,  1.3428,  ...,  0.2199, -1.5274,  0.8101],
         [-0.6008,  0.8335,  0.6227,  ...,  0.1059, -0.9803, -2.7745],
         [-0.1249, -0.1208, -0.9901,  ..., -0.844

TypeError: log_sigmoid() got an unexpected keyword argument 'dim'

In [8]:
phi, phi_IC, phi_UC = model(x)

In [9]:
phi.size()

torch.Size([10])

In [10]:
phin, phin_IC, phin_UC = model(x_neighbors)

In [11]:
phin.size()

torch.Size([1, 10])

In [15]:
x_neighbors.size()
import torch

In [24]:
torch.inner(phi, phin)

tensor([2.6093], grad_fn=<ReshapeAliasBackward0>)

In [26]:
phi_n, phi_n_IC, phi_n_UC = model(x_negative)

In [28]:
torch.inner(phi_n, phi)

tensor([ 0.0206, -3.3579, -2.3495, -1.2092, -1.9400],
       grad_fn=<ReshapeAliasBackward0>)

In [29]:
torch.inner(phi_n[0], phi)

tensor(0.0206, grad_fn=<ReshapeAliasBackward0>)

In [37]:
y > 1000

tensor(True)

In [31]:
x, y = y, x

In [32]:
x

5

In [53]:
import torch.nn.functional as F

In [57]:
test_x, test_IC = torch.ones((32, 5, 5)), torch.ones((32, 5, 5))

In [60]:
F.logsigmoid(torch.sum(torch.mul(test_x, test_IC), dim=2)).size()

torch.Size([32, 5])

In [ ]:
test_x, test_IC = torch.ones((32, 5)), torch.ones((32, 5))