In [1]:
import pandas as pd
import numpy as np

In [2]:
# read in the data
path = '/home/jimmy/CILProject22/data/raw/train_split_0.csv'

In [3]:
from src.data.Contrastive.graph_datamodule import Triplet_Dataset
dataset = Triplet_Dataset(file_path=path, n_users=1000, n_items=10000, k=2)


In [4]:
from torch.utils.data import DataLoader
#from src.data.Contrastive.graph_datamodule import collate_tuples
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [5]:
for i in dataloader:
    print(i)
    for j in i:
        print(j.size())
    break

[tensor([ 541, 7030,  815, 4289]), tensor([5186,  835, 6274,  439]), tensor([[8841],
        [ 145],
        [5706],
        [ 176]]), tensor([[ 622],
        [6832],
        [ 725],
        [7109]]), tensor([[  350,   671,   903,   743,   328],
        [ 5644,  9953,  1153,  7629,  5787],
        [   74,   465,   777,   546,   803],
        [ 1805,  1958,  2652,  7676, 10302]]), tensor([[2105, 6408, 8573, 4848, 7115],
        [  82,  384,  398,  790,  622],
        [6479, 4413, 8412, 8707, 6057],
        [ 720,  959,  968,  166,  896]]), tensor([[6820, 4792,  986,  812, 5848],
        [4617, 9342, 1718, 4813, 6461],
        [9753, 4704, 7794, 4061, 6454],
        [3773, 2493, 6325,  804, 1614]]), tensor([[5059, 3660, 5333, 5394, 7352],
        [6669, 6157,  442, 9856, 3065],
        [1899, 7718, 9683, 8593, 6949],
        [ 256, 1541, 9629,  535, 5529]])]
torch.Size([4])
torch.Size([4])
torch.Size([4, 1])
torch.Size([4, 1])
torch.Size([4, 5])
torch.Size([4, 5])
torch.Size([4, 5])
torc

In [34]:
# Create Model Object
x, y, x_neighbors, y_neighbors, x_negative, y_negative, negative_x, negative_y = dataset.__getitem__(0)

In [14]:
dataset.__getitem__(0)

(tensor(0),
 tensor(1043),
 tensor([3110]),
 tensor([518]),
 tensor([136, 759, 391, 887, 301]),
 tensor([2800, 2420, 1221, 8409, 2502]),
 tensor([7867, 8709, 5047,  334, 3306]),
 tensor([9975, 2383, 9820, 4897, 4160]))

In [6]:
from src.models.CSE.model import model
model = model()

In [7]:
for i, batch in enumerate(dataloader):
    x, y, x_neighbors, y_neighbors, x_negative, y_negative, negative_x, negative_y = batch

        # if x >= 1000:
        #     x, y, = y, x
        #     x_neighbors, y_neighbors = y_neighbors, x_neighbors
        #     x_negative, y_negative = y_negative, x_negative

    # phi_x, _, _ = model.forward(x)
    # phi_y, _,  _ = model.forward(y)
    # _, _, phi_UC = model.forward(x_neighbors)
    # _, _, phi_UC_negative = model.forward(x_negative)
    # phi_UC_negative = phi_UC_negative.transpose(0, 1)
    # print(phi_UC_negative.size())
    # _, phi_IC, _ = model.forward(y_neighbors)
    #
    # _, phi_IC_negative, _ = model.forward(y_negative)
    # print(phi_IC_negative)
    # phi_IC_negative = phi_IC_negative.transpose(0, 1)
    #
    # phi_negative_x, _, _ = model.forward(negative_x)
    # phi_negative_y, _, _ = model.forward(negative_y)
    #
    # loss = model.loss(phi_x, phi_y, phi_IC, phi_UC, phi_IC_negative, phi_UC_negative,
    #                      phi_negative_x, phi_negative_y)
    # print(loss)
    loss = model.training_step(batch, 0)
    print(loss)
    break

tensor([[[-0.2208,  1.2532, -1.6434, -1.3246, -0.5217,  0.1502, -0.2312,
           0.9629, -0.0636, -1.9534],
         [ 0.0902, -1.1097, -1.4267, -1.2040,  0.5408, -0.4654, -1.6484,
           0.1605, -0.3821, -0.8059],
         [-1.2295, -0.0309, -0.5116, -0.6153, -0.0668, -0.3575,  0.2862,
          -0.4098,  2.1030, -0.7477],
         [ 0.7814,  0.0779, -0.6621, -1.5798, -0.1848,  2.2497,  0.0161,
          -1.3767, -0.9794,  0.6265],
         [-0.6063, -1.2655,  0.5006,  0.3708, -1.8482, -0.7190, -0.0250,
           0.8847, -0.0531, -3.1203]],

        [[-0.2639, -0.7089,  0.9820, -1.5509, -0.7525, -0.9203, -1.5555,
           0.1536,  0.4680, -0.8962],
         [-0.2081,  0.6629,  1.2907,  0.4791,  0.3512,  0.0443, -0.5499,
           0.4636,  0.5690,  0.4311],
         [ 0.5282,  1.6192, -0.3959, -0.0946, -0.7529,  0.7876,  0.0381,
          -0.5775,  1.4938, -0.4123],
         [ 0.2639,  0.7648,  1.6669, -2.0692,  0.3902, -0.0187,  0.0730,
          -2.1265, -1.7263,  1.0756],

In [8]:
phi, phi_IC, phi_UC = model(x)

In [9]:
phi.size()

torch.Size([10])

In [10]:
phin, phin_IC, phin_UC = model(x_neighbors)

In [11]:
phin.size()

torch.Size([1, 10])

In [15]:
x_neighbors.size()
import torch

In [24]:
torch.inner(phi, phin)

tensor([2.6093], grad_fn=<ReshapeAliasBackward0>)

In [26]:
phi_n, phi_n_IC, phi_n_UC = model(x_negative)

In [28]:
torch.inner(phi_n, phi)

tensor([ 0.0206, -3.3579, -2.3495, -1.2092, -1.9400],
       grad_fn=<ReshapeAliasBackward0>)

In [29]:
torch.inner(phi_n[0], phi)

tensor(0.0206, grad_fn=<ReshapeAliasBackward0>)

In [37]:
y > 1000

tensor(True)

In [31]:
x, y = y, x

In [32]:
x

5

In [53]:
import torch.nn.functional as F

In [57]:
test_x, test_IC = torch.ones((32, 5, 5)), torch.ones((32, 5, 5))

In [60]:
F.logsigmoid(torch.sum(torch.mul(test_x, test_IC), dim=2)).size()

torch.Size([32, 5])

In [ ]:
test_x, test_IC = torch.ones((32, 5)), torch.ones((32, 5))