In [1]:
from graph_datamodule import Graph_Dataset
from src.models.GraphAutoencoder.model import GraphAutoencoder

FILE_PATH= '/home/jj/CILProject22/data/raw/cross_validation/test_split_0.csv'

In [2]:
d = Graph_Dataset(file_path=FILE_PATH, n_items=1000, n_users=10000)

In [3]:
g = GraphAutoencoder(file_path=FILE_PATH,n_users=10000, n_items=1000, latent_dim=100)

Creating adjacency matrices
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])


In [4]:
import torch
g.training_step(d[0], 1)

torch.Size([11000, 500])
torch.Size([1000, 100])
torch.Size([10000, 100])
torch.Size([1000, 10000, 1])
torch.Size([1000, 10000, 1])
tensor(4)
tensor(4)
tensor([2.9423], grad_fn=<SelectBackward0>)
torch.Size([])


/home/jj/CILProject22/venv/lib/python3.10/site-packages/torch/nn/functional.py:1944: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/jj/CILProject22/venv/lib/python3.10/site-packages/torch/nn/modules/loss.py:529: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


(tensor(1.1188, grad_fn=<MseLossBackward0>), tensor(1.1188))

In [6]:
torch.ones(1000, 500).transpose(0, 1).matmul(g.decoder.weight).size()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (500x100 and 1000x500)

In [7]:
g.decoder.weight.size()

torch.Size([5, 100, 100])

In [5]:
g_nll = GraphAutoencoder(file_path=FILE_PATH, n_users=10000, n_items = 1000, latent_dim=100, loss='NLL')

Creating adjacency matrices
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])
torch.Size([11000, 11000])


In [6]:
g_nll.training_step(d[0], 1)

torch.Size([11000, 500])
torch.Size([1000, 100])
torch.Size([10000, 100])
torch.Size([1000, 10000, 5])
torch.Size([1000, 10000, 5])
tensor(4)
tensor(3)
tensor([0.2224, 0.1945, 0.1872, 0.2100, 0.1859], grad_fn=<SelectBackward0>)
torch.Size([])


(tensor(-0.2100, grad_fn=<NllLossBackward0>), tensor(1.1181))

In [5]:
# x, y = torch.tensor(d[0][0]), d[1]
# mask = y != 0
# x_embeddings = g.embeddings.weight[mask]
# x_embeddings[x] = g.embeddings(torch.tensor(x))

/tmp/ipykernel_403191/1365684711.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_embeddings[x] = g.embeddings(torch.tensor(x))


In [6]:
# import torch.nn.functional as F

In [15]:
# adj = g.norm_adj[0]
# gcn1 = g.gcn1[0]
# input = F.dropout(x_embeddings, gcn1.dropout, gcn1.training)
#         #support = torch.mm(input, self.weight.weight)
# support = gcn1.weight(input)
# print(adj.size())
# print(support.size())
# output = torch.matmul(adj.to_dense(), support)

torch.Size([11000, 11000])
torch.Size([1, 11000, 100])


In [16]:
# output.size()

torch.Size([1, 11000, 100])

In [6]:
# import pandas as pd
# import torch
# df = pd.read_csv(FILE_PATH)
# print('Creating adjacency matrices')
# indices_i = []
# indices_j = []
# n_items = 1000
# for i, x in df.iterrows():
#             name, val = x['Id'], x['Prediction']
#             user, movie = name.replace('c', '').replace('r', '').split('_')
#             user, movie = int(user) - 1, int(movie) - 1
#             val = int(val)
#             indices_i.append(movie)
#             indices_j.append(user + n_items)
#             #
#             indices_i.append(user + n_items)
#             indices_j.append(movie)
#
#
# adj = torch.sparse_coo_tensor(torch.tensor([indices_i, indices_j]),
#                                                     torch.ones(size=(len(indices_i),)),
#                                                     size=[11000, 11000]).coalesce().to_sparse_csr()

Creating adjacency matrices


In [22]:
# adj = adj.to_sparse_coo()
# def normalize_adj(adj:torch.sparse.Tensor):
#     degrees = adj.to_dense().sum(dim=1)
#     degrees = torch.sqrt(degrees)
#     degrees = 1/degrees
#     degrees = degrees.unsqueeze(1)
#     normalized = degrees.transpose(0, 1).mul(degrees).to_sparse_coo()
#     print(normalized.size())
#     print(adj.size())
#     return adj.mul(normalized)
# normalize_adj(adj)

torch.Size([11000, 11000])
torch.Size([11000, 11000])


tensor(indices=tensor([[    0,     0,     0,  ..., 10999, 10999, 10999],
                       [ 1066,  1089,  1113,  ...,   658,   813,   840]]),
       values=tensor([0.0445, 0.0184, 0.0263,  ..., 0.0117, 0.0158, 0.0182]),
       size=(11000, 11000), nnz=470782, layout=torch.sparse_coo)

In [24]:
# adj

tensor(indices=tensor([[    0,     0,     0,  ..., 10999, 10999, 10999],
                       [ 1066,  1089,  1113,  ...,   658,   813,   840]]),
       values=tensor([1., 1., 1.,  ..., 1., 1., 1.]),
       size=(11000, 11000), nnz=470782, layout=torch.sparse_coo)

In [11]:
# import torch
# for j in range(len(d)):
#     idx, connections = d[j]
#     if idx < 1000:
#         maxes, indices = torch.max(connections > 0, dim=0)
#         if indices < 1000:
#             print(f"{idx } Violation")
#         else:
#             print(f'{idx} cleared')
#     else:
#         maxes, indices = torch.max(connections > 0, dim=0)
#         if indices >=  1000:
#             print(f'{idx} violation')
#         else:
#             print(f'{idx} {indices} cleared')

0 cleared
1 cleared
2 cleared
3 cleared
4 cleared
5 cleared
6 cleared
7 cleared
8 cleared
9 cleared
10 cleared
11 cleared
12 cleared
13 cleared
14 cleared
15 cleared
16 cleared
17 cleared
18 cleared
19 cleared
20 cleared
21 cleared
22 cleared
23 cleared
24 cleared
25 cleared
26 cleared
27 cleared
28 cleared
29 cleared
30 cleared
31 cleared
32 cleared
33 cleared
34 cleared
35 cleared
36 cleared
37 cleared
38 cleared
39 cleared
40 cleared
41 cleared
42 cleared
43 cleared
44 cleared
45 cleared
46 cleared
47 cleared
48 cleared
49 cleared
50 cleared
51 cleared
52 cleared
53 cleared
54 cleared
55 cleared
56 cleared
57 cleared
58 cleared
59 cleared
60 cleared
61 cleared
62 cleared
63 cleared
64 cleared
65 cleared
66 cleared
67 cleared
68 cleared
69 cleared
70 cleared
71 cleared
72 cleared
73 cleared
74 cleared
75 cleared
76 cleared
77 cleared
78 cleared
79 cleared
80 cleared
81 cleared
82 cleared
83 cleared
84 cleared
85 cleared
86 cleared
87 cleared
88 cleared
89 cleared
90 cleared
91 cleare

In [12]:
# import time
# t = time.time()
# for i in range(len(d)):
#     print(d[0][1] != 0)
# print(time.time()-t)

tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  ..., False, False, False])
tensor([False, False, False,  .

In [13]:
from src.models.GraphAutoencoder.model import GraphAutoencoder

ImportError: cannot import name 'normalize_adj' from 'utils' (unknown location)

In [ ]:
auto_